### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rafadsm** [cmberryau/rename_dll#1]
Hello, I found on the internet that you posted this repository, I had a problem executing the script, could you help me? Thank you!

![err](https://user-images.githubusercontent.com/25557084/56475714-873ceb80-6462-11e9-8b1a-8ddf78ea3224.png)

my folder:
![folder](https://user-images.githubusercontent.com/25557084/56475736-e3a00b00-6462-11e9-86cf-086a19c8ebbe.png)

**Comment by varhub** [comment]
@FinnProjects , I guess you are using Python 3 instead Python 2. Try again with proper python version.
By the way fix is stupid simple*:
`lines = out.decode().split('\n')`

(*) until you get slapped by file encoding, that might be a possibility ;) ;)
